kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      name: nginx
      labels:
        tier: backend
        app: v1
    spec:
      containers:
        - image: nginx:1.23.0
          name: nginx
          ports:
            - containerPort: 80

